name: Deploy to Fly
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout focal-fso repository
        uses: actions/checkout@v2
        with:
          repository: glleroux/focal-front
          token: ${{ secrets.PAT }} # Replace with the name of your PAT secret

      - name: Build UI
        run: |
          npm install
          npm run build

      - name: Checkout focal-server repository
        uses: actions/checkout@v2
        with:
          repository: glleroux/focal

      - name: Remove current build directory
        run: |
          rm -rf build

      - name: Copy build directory to focal-server repository
        run: |
          cp -r ../focal-front/build/* build/

      - name: Deploy to Fly
        run: |
          npm install
          fly deploy --token ${{ secrets.FLY_API_TOKEN }}
