name: Deploy to Fly
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout focal-fso repository
        uses: actions/checkout@v3
        with:
          repository: glleroux/focal-front
          token: ${{ secrets.PAT }} # Replace with the name of your PAT secret
          path: focal-front # specify the path to checkout the repository to

      - name: Build UI
        working-directory: ./focal-front # set the working directory to focal-front
        run: |
          npm install
          npm run build

      - name: Checkout focal-server repository
        uses: actions/checkout@v3
        with:
          repository: glleroux/focal
          path: focal

      - name: Remove current build directory
        working-directory: ./focal
        run: |
          rm -rf build

      - name: Copy build directory to focal-server repository
        working-directory: ./focal
        run: |
          cp -r ../focal-front/build/* build/

      - name: Deploy to Fly
        working-directory: ./focal
        run: |
          npm install
          fly deploy --token ${{ secrets.FLY_API_TOKEN }}
